### ISSUE TITLE
Prov-vis fails when used from ES build

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/prov-vis#36]
The JSON schema it uses is in the UMD, but isn't in the ES build, so it fails.

**Comment by mccalluc** [comment]
@john-conroy : Mark Keller has been improving the build for vitessce, so you might ping him and see what he's learned about the best way to do this.

There will be corresponding tweaks in portal-ui that will be needed, once the fixes have been made here. Keep this open until it works end-to-end.

**Comment by mccalluc** [comment]
@john-conroy : I think you fixed this in #37?

**Comment by john-conroy** [comment]
I believe so, I can verify tomorrow.
